### ISSUE TITLE
Error when installing on socailize on my Meteor project

### ISSUE THREAD

**Issue by jerocosio** [copleykj/socialize-friendships#7]
Hi, I'm getting this error when I add the socialize package to my Meteor project, any idea how can I solve it? Thanks in advance! 

PD: Great update on the readme, and amazing video explaining how to use this package!

```
W20150906-18:44:40.366(-5)? (STDERR) /Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.4.mdycm0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150906-18:44:40.367(-5)? (STDERR)                        throw(ex);
W20150906-18:44:40.367(-5)? (STDERR)                              ^
W20150906-18:44:40.367(-5)? (STDERR) Error: A method named 'getServerTime' is already defined
W20150906-18:44:40.367(-5)? (STDERR)     at packages/ddp/livedata_server.js:1461:1
W20150906-18:44:40.367(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150906-18:44:40.367(-5)? (STDERR)     at [object Object]._.extend.methods (packages/ddp/livedata_server.js:1459:1)
W20150906-18:44:40.367(-5)? (STDERR)     at Object.Meteor.methods (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:157:1)
W20150906-18:44:40.367(-5)? (STDERR)     at Package (packages/socialize:server-time/server/server-time.js:1:1)
W20150906-18:44:40.367(-5)? (STDERR)     at /Users/jeronimocosio/vynomvp/vynomvp/.meteor/local/build/programs/server/packages/socialize_server-time.js:57:4
W20150906-18:44:40.367(-5)? (STDERR)     at /Users/jeronimocosio/vynomvp/vynomvp/.meteor/local/build/programs/server/packages/socialize_server-time.js:66:3
W20150906-18:44:40.368(-5)? (STDERR)     at /Users/jeronimocosio/vynomvp/vynomvp/.meteor/local/build/programs/server/boot.js:222:10
W20150906-18:44:40.368(-5)? (STDERR)     at Array.forEach (native)
W20150906-18:44:40.368(-5)? (STDERR)     at Function._.each._.forEach (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.4.mdycm0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
```

**Comment by copleykj** [comment]
Oh, I see.. It looks as if this is a Meteor.methods method name collision with another package. I'll push out a fix for this ASAP.

**Comment by copleykj** [comment]
Just pushed out a new version of socialize:server-time which should fix this issue.

**Comment by jerocosio** [comment]
Wow! That was fast, thanks! ;)

**Comment by copleykj** [comment]
You're very welcome.. Have to be fast, Can't have another dev stalled on a
project for days while waiting on a fix for a package I've authored :)
